services:
  postgres:
    image: postgres
    container_name: hospital
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: nimda
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres

volumes:
  postgres_data:
    driver: local

networks:
  postgres:
    driver: bridge